block-list-secret-scan: []
branch: master
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- all
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
- CKV2_AWS_39
- CKV2_AWS_38
summary-position: top
