

repos:
    # Disabled cause they all rely on hooks from the repo
  # and installing checkov in a python venv is a disaster
# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.80.0
#   hooks:
#     - id: terraform_fmt
    # - id: terraform_checkov
    #   language: system
    # - id: infracost_breakdown
    #   args:
    #     - "--args=--config-file=infracost.yml"
    #   verbose: true

- repo:  https://github.com/bridgecrewio/checkov
  rev: 2.3.281
  hooks:
  - id: checkov

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: detect-aws-credentials
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-json
  - id: pretty-format-json
    args:
      - "--autofix"
  - id: trailing-whitespace
