
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
    - id: terraform_fmt
    - id: terraform_checkov
    - id: infracost_breakdown
      args:
        - "--args=--config-file=infracost.yml"
      verbose: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: detect-aws-credentials
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-json
  - id: pretty-format-json
    args:
      - "--autofix"
  - id: trailing-whitespace

# So ref 3.0.0 is bugged  https://github.com/kamadorueda/alejandra/issues/354
# But we can't use main cause the version of pre-commit the hook requires is _slightly_
#   higher than what is presently provided with nixpkgs 🙄
# So also, something's cooked with pre-commit autoupdate and it actually rolls
#   v3.0.0 *back*, all the way to v1.3.0. I've not seen an issue for it
#   and the tags look to be chronologically correct...
# - repo: https://github.com/kamadorueda/alejandra
#   rev: main
#   hooks:
#   - id: alejandra
