[tool.poetry]
name = "aws-bootstrap"
version = "0.1.0"
description = "Declarative infrastructure for my personal AWS account(s) and hosting"
authors = ["Richtman, Ariel <10679234+arichtman@users.noreply.github.com>"]
license = "GPL-2."

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"
commitizen = "^2.27.1"
checkov = "^2.0.1220"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
