
FROM rendanic/terratools:latest

COPY pyproject.toml poetry.lock ./

RUN dnf install -y tar \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && echo 'export PATH="/root/.local/bin:$PATH"' >> ~/.bashrc \
    && export PATH="/root/.local/bin:$PATH" \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --quiet \
    && curl -L https://raw.githubusercontent.com/warrensbox/hubapp/release/install.sh | bash - \
# This will fail on a rename
    && hubapp upgrade infracost/infracost \
# No way to specify version on Hubapp install but we know it'll only create one directory
    && ln -s ~/.infracost/files_*/infracost-linux-amd64 ~/.local/bin/infracost \
    && infracost completion --shell bash >> ~/.profile \
    && hubapp upgrade minamijoyo/tfupdate \
    && hubapp upgrade terraform-docs/terraform-docs \
    && terraform-docs completion bash >> ~/.profile
